export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_REG_IN = 'USER_REG_IN';
export const USER_REG_OUT = 'USER_REG_OUT';

export const INPUT_LOGIN_CHANGE = 'INPUT_LOGIN_CHANGE';
export const INPUT_PASSWORD_CHANGE = 'INPUT_PASSWORD_CHANGE';

export const INPUT_LOGIN_REG = 'INPUT_LOGIN_REG';
export const INPUT_PASSWORD_REG = 'INPUT_PASSWORD_REG';
export const INPUT_EMAIL_REG = 'INPUT_EMAIL_REG';

export const INPUT_COMMENT = 'INPUT_COMMENT';
export const SEND_COMMENT = 'SEND_COMMENT';

export const GET_PLACEHOLDER_LOADING = 'GET_PLACEHOLDER_LOADING';
export const GET_PLACEHOLDER_SUCCESS = 'GET_PLACEHOLDER_SUCCESS';
export const GET_PLACEHOLDER_FAILED = 'GET_PLACEHOLDER_FAILED';

export const LIKES_CHANGE = 'LIKES_CHANGE';
export const CLEAR_FORM = 'CLEAR_FORM';
